### ISSUE TITLE
GPU WON't CONNECT

### ISSUE THREAD

**Issue by DrukCG** [edenaion/EZ-CorridorKey#25]
<img width="2559" height="1439" alt="Image" src="https://github.com/user-attachments/assets/f08dd83d-1bab-4a10-81a8-698064299369" /> ## Description
## Description
Bug: GVM not using GPU on Windows — VRAM stuck at 0.2/8GB System:
OS: Windows 11
GPU: NVIDIA RTX 4070 Laptop GPU (8GB VRAM)
Python: 3.13
PyTorch: 2.10.0+cu128
CUDA available: True
Install method: Conda (ezcorridorkey env) Problem: GVM Alpha job runs for 1.5+ hours on 150 frames but VRAM never exceeds 0.2/8GB. torch.cuda.is_available() returns True and GPU is detected correctly, so the issue is inside GVM's model loading — it appears to be running on CPU despite cuda being the compute device. Evidence:
Log shows: Compute device: cuda ✅
VRAM monitor shows: 0.2/8.0GB the entire job ❌
150 frames took 1.5+ hours (should be ~5-10 mins on GPU) Expected: GVM should load models onto CUDA and use 3-4GB VRAM Actual: Models appear to stay on CPU, VRAM barely used Does this need an explicit .to(device) call in gvm_core/wrapper.py? where exactly do i post this?

## System Info
- **App Version:** 1.1.2
- **OS:** Windows-11-10.0.26200-SP0
- **Python:** 3.12.12
- **PyTorch:** 2.10.0+cu128
- **CUDA:** 12.8
- **GPU:** NVIDIA GeForce RTX 4070 Laptop GPU
- **VRAM:** 8.0 GB total, 0.2 GB used
- **Display:** 1707x960

## System Info
- **App Version:** 1.1.2
- **OS:** Windows-11-10.0.26200-SP0
- **Python:** 3.12.12
- **PyTorch:** 2.10.0+cu128
- **CUDA:** 12.8
- **GPU:** NVIDIA GeForce RTX 4070 Laptop GPU
- **VRAM:** 8.0 GB total, 0.2 GB used
- **Display:** 1707x960

**Comment by DrukCG** [comment]
[

<img width="2559" height="1439" alt="Image" src="https://github.com/user-attachments/assets/1cf5c72e-16a7-452e-9ac9-8a1f6272b40d" />

](url) Thank you it is working now, running the test 🫡
